openapi: '3.0.3'
info:
  description: |
    The Mojos serverless API can provide projected data that may be easier to use for non-blockchain-native clients.

    ## Function Versioning
    `v0-` prefixed functions are in development and may change before becoming finalized.
  version: '0.1.0'
  title: 'Mojos Serverless API'
  license:
    name: 'CC0'
tags:
  - name: 'Address Data'
    description: 'Functions that check status of Ethereum addresses'
  - name: 'Governance'
    description: 'Functions for fetching governance data'
  - name: 'Mojos'
    description: 'Information about Mojo tokens'
  - name: 'Cryptography'
    description: 'Functions for verifying identity'
servers:
  - url: 'https://mojos.wtf/.netlify/functions/'
    description: Production Deployment
paths:
  /v0-is-mojo-owner:
    post:
      tags:
        - 'Address Data'
      summary: 'Check if an Ethereum address owns a Mojo'
      operationId: 'isMojoOwner'
      requestBody:
        description: The Ethereum address to check for Mojo ownership
        content:
          'text/plain':
            schema:
              type: string
            example: '0x2536c09e5f5691498805884fa37811be3b2bddb4'
      responses:
        '200':
          description: 'Does address own a Mojo'
          content:
            application/json:
              schema:
                type: boolean
              example: true
  /v0-is-mojo-delegate:
    post:
      tags:
        - 'Address Data'
      summary: 'Check if an Ethereum is delegated the voting power of a Mojo'
      operationId: 'isMojoDelegate'
      requestBody:
        description: The Ethereum address to check for Mojo delegation
        content:
          'text/plain':
            schema:
              type: string
            example: '0x75ee6eb3d8dacf41ee2e5307090b197d3e1cca6e'
      responses:
        '200':
          description: 'Is address delegated the voting power of a Mojo'
          content:
            application/json:
              schema:
                type: boolean
              example: true
  /v0-mojo-owners:
    get:
      summary: 'Ethereum addresses that own Mojos or are delegated voting power'
      tags:
        - 'Address Data'
      operationId: 'getMojoOwners'
      responses:
        '200':
          description: 'Lite Mojo information including owners and delegates'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LiteMojo'
  /v0-mojo-votes:
    get:
      summary: 'All Mojos and their votes'
      tags:
        - 'Governance'
      operationId: 'getMojoVotes'
      responses:
        '200':
          description: 'All Mojos and how the votes they cast in Mojos governance proposals'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MojoWithVotes'
  /v0-proposal-votes:
    get:
      summary: 'All governance proposals and their votes'
      tags:
        - 'Governance'
      operationId: 'getProposalVotes'
      responses:
        '200':
          description: 'All governance proposals and an array of votes cast'
          content:
            application/json:
              schema:
                type: object
  /v0-mojo-seeds:
    get:
      summary: 'All Mojos and their seeds'
      tags:
        - 'Mojos'
      operationId: 'getMojoSeeds'
      responses:
        '200':
          description: 'All Mojos and their seeds'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MojoWithSeeds'
  /v0-verify-signature:
    post:
      summary: 'Verify an ethereum signed message'
      tags:
        - 'Cryptography'
      operationId: 'getProposalVotes'
      parameters:
        - name: fetchParticipation
          in: 'query'
          description: If set to true and the signature is valid, fetch to see if the signer owns or is delegated a Mojo
          schema:
            type: boolean
          example: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifySignatureRequest'
            example:
              message: "I am 0x28f1F4ea77Af433c45366151F6f9906435d9DB19\n\nThis is me testing the Mojos serverless API"
              signer: '0x28f1F4ea77Af433c45366151F6f9906435d9DB19'
              signature": '0xc82fd716033ae41efd155258622a6c7d0d42ce56d03d6ba0bef1091d54675c4872e99f5718dfe0cb1a1a8dfd8d62fd35dfa10445d40e001174756a7059dd80d81b'
      responses:
        '200':
          description: 'All governance proposals and an array of votes cast'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifySignatureResponse'
components:
  schemas:
    NormalizedVote:
      type: object
      description: A Mojos proposal vote
      properties:
        proposalId:
          type: integer
          format: uint256
          description: The ID of the Mojos Governance proposal
        supportDetailed:
          type: integer
          format: uint256
          description: 'The integer support value: against (0), for (1), or abstain (2)'
    Seed:
      type: object
      description: The attributes that make up a Mojo's seed
      properties:
        face:
          type: integer
        body:
          type: integer
        background:
          type: integer
        bodyAccessory:
          type: integer
        headAccessory:
          type: integer
    NormalizedMojo:
      type: object
      description: A Mojo record
      properties:
        id:
          type: integer
          format: uint256
        owner:
          type: string
        delegatedTo:
          type: string
          description: The address that the Mojo's voting power is delegated to
        votes:
          type: array
          items:
            $ref: '#/components/schemas/NormalizedVote'
        seed:
          $ref: '#/components/schemas/Seed'
    ProposalVote:
      type: object
      description: How a Mojo voted on a governance proposal
      properties:
        mojoId:
          type: integer
        owner:
          type: string
          description: The owner of the Mojo
        delegatedTo:
          type: string
          description: The Ethereum address the Mojo's voting power is delegated
        supportDetailed:
          type: integer
          description: 'The integer support value: against (0), for (1), or abstain (2)'
    ProposalVotes:
      type: object
      description: A map of Mojo governance proposal ID to an array of votes
    MojoWithSeeds:
      type: object
      description: A Mojo and its seed attributes
      properties:
        id:
          type: integer
          format: uint256
        seed:
          type: object
          $ref: '#/components/schemas/Seed'
    MojoWithVotes:
      type: object
      description: How a Mojo has voted on Mojos governance proposals
      properties:
        id:
          type: integer
          format: uint256
        owner:
          type: string
          description: The owner of the Mojo
        delegatedTo:
          type: string
          description: The Ethereum address a Mojo's voting power has been delegated to
        votes:
          type: array
          items:
            $ref: '#/components/schemas/NormalizedVote'
    LiteMojo:
      type: object
      properties:
        id:
          type: integer
          format: uint256
        owner:
          type: string
          description: The owner of the Mojo
        delegatedTo:
          type: string
          description: The Ethereum address a Mojo's voting power has been delegated to
    VerifySignatureRequest:
      type: object
      required:
        - 'message'
        - 'signature'
        - 'signer'
      properties:
        message:
          type: string
          description: The original signed message
        signature:
          type: string
          description: Signature submitted for verification
        signer:
          type: string
          description: The address attesting to have signed the message
    VerifySignatureResponse:
      type: object
      required:
        - 'message'
        - 'signature'
        - 'providedSignature'
        - 'recoveredAddress'
        - 'validSignature'
      properties:
        message:
          type: string
          description: The original signed message
        signature:
          type: string
          description: Signature submitted for verification
        providedSigner:
          type: string
          description: The signer address provided in the request
        recoveredAddress:
          type: string
          description: The address recovered from the signature
        validSignature:
          type: boolean
          description: If the supplied signature is valid
        isMojoOwner:
          type: boolean
          description: If the signature is valid and the address owns a Mojo
        isMojoDelegate:
          type: boolean
          description: If the signature is valid and the address is delegated a Mojo
